---
AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.5

Naming/FileName:
  Enabled: false

Metrics/LineLength:
  Enabled: false
