" vim:fdm=marker ft=vim:

if has('vim_starting')
  scriptencoding utf-8
endif

set background=dark

if has('gui_running')
  set guifont=Sauce\ Code\ Pro\ Nerd\ Font\ Complete:h18
endif

if has('termguicolors')
  set termguicolors
else
  set t_Co=256
endif

call minpac#add('skywind3000/asyncrun.vim')
call minpac#add('vim-airline/vim-airline')
call minpac#add('vim-airline/vim-airline-themes')
call minpac#add('ryanoasis/vim-devicons')
call minpac#add('chriskempson/base16-vim')

if exists('g:loaded_webdevicons')
  let g:webdevicons_enable = 1

  if exists('g:loaded_nerd_tree')
    let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
    let g:WebDevIconsNerdTreeGitPluginForceVAlign = 1
    let g:webdevicons_enable_nerdtree = 1
    let g:webdevicons_conceal_nerdtree_brackets = 1
  endif

  let g:WebDevIconsUnicodeDecorateFileNodes = 1
  let g:WebDevIconsUnicodeGlyphDoubleWidth = 1
endif

if exists('g:loaded_nerd_tree')
  let g:NERDTreeDirArrowCollapsible = '▾'
  let g:NERDTreeDirArrowExpandable = '▸'
end

if exists('g:loaded_airline')
  let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
  let g:airline_highlighting_cache = 1
  let g:airline_powerline_fonts = 1

  if exists('g:loaded_webdevicons')
    let g:webdevicons_enable_airline_statusline = 1
    let g:webdevicons_enable_airline_tabline = 1
  endif

  if exists('g:loaded_airline_themes')
    let g:airline_theme = 'base16_tomorrow'
  endif
endif

let g:base16colorspace = 256

colorscheme base16-tomorrow-night
